elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
logstash:
  image: logstash
  links:
    - elasticsearch
  ports:
    - "5000:5000"
  command: logstash -f /etc/logstash/logstash.conf
  volumes:
    - logstash/etc/:/etc/logstash/
kibana:
  image: kibana
  links: 
    - elasticsearch
  ports:
    - "5601:5601"
