elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
logstash:
  image: logstash:1.5
  links:
    - elasticsearch
  ports:
    - "5000:5000"
  command: logstash -f /etc/logstash/logstash.conf
  volumes:
    - ./logstash/etc/:/etc/logstash/
kibana:
  image: kibana:4.1
  links: 
    - elasticsearch
  ports:
    - "5601:5601"
